name: find_room
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.7.0
  firebase_storage: ^1.0.4
  image_picker: ^0.4.12+1
  json_serializable: ^2.0.1 #flutter packages pub run build_runner build
  distinct_value_connectable_observable: ^2.0.0+2
  shared_preferences: ^0.4.3
  flutter_swiper: ^1.1.4
  intl: ^0.15.7
  tuple: ^1.0.2
  collection: ^1.14.11
  cached_network_image: ^0.5.1
  wave: ^0.0.8
  google_sign_in: ^3.2.4
  flutter_facebook_login: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_appbar_image.jpg
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.ttf
        - asset: assets/fonts/SF-Pro-Text-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.ttf
          weight: 700

